<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56539b37a2804',
	'title' => 'Course',
	'fields' => array (
		array (
			'key' => 'field_56549f139e559',
			'label' => 'Units',
			'name' => 'units',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56539b37b0c0b',
			'label' => 'Units',
			'name' => 'units_repeater',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56539b37b40ed',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Unit',
			'sub_fields' => array (
				array (
					'key' => 'field_56539b37b40ed',
					'label' => 'Unit Title',
					'name' => 'unit_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_565a553d0797b',
					'label' => 'Unit ID',
					'name' => 'unit_id',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => 'acf-course-unit-id',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Will be filled automatically ...',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56539b37b4115',
					'label' => 'Items',
					'name' => 'unit_items',
					'type' => 'flexible_content',
					'instructions' => 'Add Lesson Videos and Quizzes.
Use Headlines to separate content thematically.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'button_label' => 'Add Item',
					'min' => '',
					'max' => '',
					'layouts' => array (
						array (
							'key' => '565352d8e583c',
							'name' => 'item_headline',
							'label' => 'Headline',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_56539b37ba7a6',
									'label' => 'Headline Title',
									'name' => 'headline_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '565352fa40a05',
							'name' => 'item_lesson',
							'label' => 'Video Lesson',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_56539b37ba7ce',
									'label' => 'Choose Lesson',
									'name' => 'choose_lesson',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
										0 => 'lesson',
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'id',
									'ui' => 1,
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '5653530b40a06',
							'name' => 'item_quizz',
							'label' => 'Quizz',
							'display' => 'row',
							'sub_fields' => array (
								array (
									'key' => 'field_56539b37ba7ed',
									'label' => 'Choose Quizz',
									'name' => 'choose_quizz',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
										0 => 'quizz',
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'id',
									'ui' => 1,
								),
							),
							'min' => '',
							'max' => '',
						),
					),
				),
				array (
					'key' => 'field_5653a2b5b8dda',
					'label' => 'Status',
					'name' => 'unit_status',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 60,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'disabled' => 'disabled',
						'scheduled' => 'Scheduled',
						'public' => 'Public',
						'locked' => 'To Unlock',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'disabled',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'field_5653a3a235e26',
					'label' => 'Release Date',
					'name' => 'unit_release_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5653a2b5b8dda',
								'operator' => '==',
								'value' => 'scheduled',
							),
						),
					),
					'wrapper' => array (
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 0,
				),
				array (
					'key' => 'field_565611c7995ed',
					'label' => 'Unlock Info',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5653a2b5b8dda',
								'operator' => '==',
								'value' => 'locked',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'This Unit will be Locked. The User needs to complete the previous Unit first to unlock this Unit. It would be advisable to lock all the following Units, too.',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
			),
		),
		array (
			'key' => 'field_56549f489e55a',
			'label' => 'Information about Course',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56539bb430d58',
			'label' => 'Course Description',
			'name' => 'course_description',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 260,
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56731c3b4ebfd',
			'label' => 'Color Palette',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Create an individual Color Palette for the course.
A useful tool to create nice color compositions: <a href="https://kuler.adobe.com/" target="_blank">Adobe Kuler</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_5671b20315542',
			'label' => 'Main Color',
			'name' => 'color_main',
			'type' => 'color_picker',
			'instructions' => 'Choose a strong primary color. Try to avoid green and red.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'default_value' => '#4FA5B8',
		),
		array (
			'key' => 'field_5671b22a15543',
			'label' => 'Secondary Color',
			'name' => 'color_secondary',
			'type' => 'color_picker',
			'instructions' => 'Choose a color with the same hue than the main color, but very subtle (light).',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ababab',
		),
		array (
			'key' => 'field_5671b24215544',
			'label' => 'Complementary Color',
			'name' => 'color_comp',
			'type' => 'color_picker',
			'instructions' => 'Choose a complementary to the main color.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'default_value' => '#F2A200',
		),
		array (
			'key' => 'field_56549f689e55b',
			'label' => 'Course Badge',
			'name' => 'img_course_badge',
			'type' => 'image',
			'instructions' => 'The course badge should be a PNG with exactly 320x320 px. It should be a perfectly round shape on transparent background. Please use a PNG-8 compression to keep the file size below 100 Kb.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 320,
			'min_height' => 320,
			'min_size' => '',
			'max_width' => 320,
			'max_height' => 320,
			'max_size' => 1,
			'mime_types' => 'png',
		),
		array (
			'key' => 'field_5671b18715541',
			'label' => 'Course Header',
			'name' => 'img_course_header',
			'type' => 'image',
			'instructions' => 'The Course Header image should be 1800x600 px, that is a ratio of 4:1.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 1800,
			'min_height' => 600,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => 1,
			'mime_types' => 'jpg',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'course',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56648e82406a7',
	'title' => 'Lesson used in ...',
	'fields' => array (
		array (
			'key' => 'field_56648ec0f568f',
			'label' => 'Course:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '<a href="#">Bible Basics</a>',
			'new_lines' => '',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_566498bf5b52a',
			'label' => 'Unit:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '1. <a href="#">Introduction, the Kingdom of God and Religious Liberty</a>',
			'new_lines' => '',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_566498ca5b52b',
			'label' => 'Video:',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '1.5',
			'new_lines' => '',
			'esc_html' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'lesson',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56536f2021cbe',
	'title' => 'Quizz',
	'fields' => array (
		array (
			'key' => 'field_56536f244dc9b',
			'label' => 'Questions',
			'name' => 'questions_repeater',
			'type' => 'repeater',
			'instructions' => 'It is advisable to add more questions than are shown to the user to make it more unlikely to pass by trial and error.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56536fe04dc9d',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Question',
			'sub_fields' => array (
				array (
					'key' => 'field_56536fe04dc9d',
					'label' => 'Question Text',
					'name' => 'question_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'What is the color of grass?',
					'maxlength' => '',
					'rows' => 1,
					'new_lines' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_565370e7d72b3',
					'label' => 'Answers',
					'name' => 'question_answers',
					'type' => 'textarea',
					'instructions' => 'Each line is a possible answer. Mark the correct answer with *.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '*Green',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'wpautop',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_56536f904dc9c',
			'label' => 'Required Questions',
			'name' => 'required_questions',
			'type' => 'number',
			'instructions' => 'How many questions is the user required to answer?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 40,
				'class' => '',
				'id' => '',
			),
			'default_value' => 5,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Questions',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_565372c6fa1c4',
			'label' => 'Some Text',
			'name' => 'some_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 60,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'quizz',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_565373ecac97d',
	'title' => 'Video Lesson',
	'fields' => array (
		array (
			'key' => 'field_565373ff396fe',
			'label' => 'Video Status',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 40,
				'class' => '',
				'id' => '',
			),
			'message' => '– Status: OK –
200 MB – 23:00 min',
			'new_lines' => 'br',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_5653741a396ff',
			'label' => 'Video File',
			'name' => 'video_file',
			'type' => 'select',
			'instructions' => 'Choose Video File',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 60,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5653743a39700',
			'label' => 'Video Description',
			'name' => 'video_description',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_5653744f39701',
			'label' => 'Video Attachment',
			'name' => 'video_attachment',
			'type' => 'file',
			'instructions' => 'Attach the Manuscript for the Video. Only .pdf is allowed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'pdf',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'lesson',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;